source "https://rubygems.org"

gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

# Install gems to local vendor/bundle directory to avoid permission issues
# Run: bundle config set --local path 'vendor/bundle'
# Then: bundle install

